# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shattori <shattori@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/08/05 19:59:52 by shattori          #+#    #+#              #
#    Updated: 2025/08/05 20:07:03 by shattori         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		:=	megaphone

CXXFLAGS	:=	-Wall -Wextra -Werror 
CXXFLAGS	+=	-std=c++98 -pedantic

SRCS		:=	megaphone.cpp

$(NAME): $(SRCS)

.PHONY: clean
clean: $(NAME)
	$(RM) $^
	